In [1]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
# Вектор з 10 випадковими значеннями в діапазоні від 0 до 1
vector = np.random.rand(10)

print("Тип даних вектора:", type(vector))
print("Розмір вектора: ", vector.shape)
print("Вектор:", vector)

Тип даних вектора: <class 'numpy.ndarray'>
Розмір вектора:  (10,)
Вектор: [0.44242955 0.87094724 0.84984115 0.38015224 0.82266712 0.1131045
 0.91338808 0.62528154 0.37771829 0.46153463]


In [3]:
# Створимо матрицю 3x3 з заданими значеннями
matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

print("Тип даних матриці: ", type(matrix))
print("Розмір матриці: ", matrix.shape)
print("Матриця: ", matrix)

Тип даних матриці:  <class 'numpy.ndarray'>
Розмір матриці:  (3, 3)
Матриця:  [[11 14 17]
 [20 23 26]
 [29 32 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [4]:
# 1. Додаємо до кожного значення вектора число 10 і округлюємо до 2 знаків після коми
vector = vector + 10
vector = np.round(vector, 2)

print("1. Вектор з доданими 10 і округленням до 2 знаків після коми:", vector)

1. Вектор з доданими 10 і округленням до 2 знаків після коми: [10.44 10.87 10.85 10.38 10.82 10.11 10.91 10.63 10.38 10.46]


In [5]:
# 2. Множимо кожен елемент matrix на 2
matrix = matrix * 2

print("2. Матриця, помножена на 2:", matrix)

2. Матриця, помножена на 2: [[22 28 34]
 [40 46 52]
 [58 64 70]]


In [6]:
# 3. Створюємо новий вектор, що містить квадрат кожного vector
vector_squared = vector ** 2

print("3. Вектор квадратів елементів vector:", vector_squared)

3. Вектор квадратів елементів vector: [108.9936 118.1569 117.7225 107.7444 117.0724 102.2121 119.0281 112.9969
 107.7444 109.4116]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [7]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [8]:
# 1. Множення матриць A і B

# Перевірка розмірностей матриць
if A.shape[1] != B.shape[0]:
    raise ValueError("Неможливо помножити матриці: розмірності неспівпадають.")

# Множення матриць A та B
result_matrix = np.dot(A, B)

# Виведемо результуючу матрицю
print("Множення матриць A і B:", result_matrix)

Множення матриць A і B: [[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]


In [9]:
# 2. Множення вектора С на матрицю result_matrix

# Перевірка розмірностей вектора і матриці
if result_matrix.shape[1] != C.shape[0]:
    raise ValueError("Неможливо помножити матрицю та вектор: розмірності неспівпадають.")

# Множення result_matrix на вектор C
final_result = np.dot(result_matrix, C)

# Виведення кінцевого результату
print("Результат:", final_result)

ValueError: Неможливо помножити матрицю та вектор: розмірності неспівпадають.

In [10]:
# 3. Множення матриці D на матрицю result_matrix

# Перевірка розмірностей матриць
if result_matrix.shape[1] != D.shape[0]:
    raise ValueError("Неможливо помножити матрицю та вектор: розмірності неспівпадають.")

# Множення result_matrix на матрицю D
final_result = np.dot(result_matrix, D)

# Виведення кінцевого результату
print("Результат:", final_result)

ValueError: Неможливо помножити матрицю та вектор: розмірності неспівпадають.


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [11]:
# 1. Транспонування result_matrix
result_matrix_T = result_matrix.T

print("Оригінальна матриця result_matrix", result_matrix, sep='\n')
print("Транспонована матриця result_matrix", result_matrix_T, sep='\n')

Оригінальна матриця result_matrix
[[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]
Транспонована матриця result_matrix
[[0.232  0.3061 0.1393]
 [0.1627 0.4867 0.2261]
 [0.2145 0.633  0.294 ]]


In [12]:
# 2. Транспонування вектора vector

vector_T = vector.T

print("Оригінальний вектор vector", vector, sep='\n')
print("Транспонований  вектор vector", vector_T, sep='\n')


Оригінальний вектор vector
[10.44 10.87 10.85 10.38 10.82 10.11 10.91 10.63 10.38 10.46]
Транспонований  вектор vector
[10.44 10.87 10.85 10.38 10.82 10.11 10.91 10.63 10.38 10.46]


При транспонуванні вектора ми не бачимо змін

In [13]:
# 3. Операція numpy.expand_dims над вектором vector

# Створюємо вектор-стовпець за допомогою numpy.expand_dims
column_vector = np.expand_dims(vector, axis=1)

print("Оригінальний вектор vector:", vector)
print("Cвектор-стовпець з numpy.expand_dims:", column_vector)

print("Розмір оригінального vector:", vector.shape)
print("Розмір вектора-стовпця:", column_vector.shape)

Оригінальний вектор vector: [10.44 10.87 10.85 10.38 10.82 10.11 10.91 10.63 10.38 10.46]
Cвектор-стовпець з numpy.expand_dims: [[10.44]
 [10.87]
 [10.85]
 [10.38]
 [10.82]
 [10.11]
 [10.91]
 [10.63]
 [10.38]
 [10.46]]
Розмір оригінального vector: (10,)
Розмір вектора-стовпця: (10, 1)


при використанні `numpy.expand_dims` ми змінюємо розмір (перевертаємо) вектор з вектора-рядка на вектор-стовпець

In [14]:
# 4. Транспонуємо column_vector

column_vector_T = column_vector.T

print("Nhfycgjyjdfybq column vector:", column_vector_T)
print("Transposed column vector shape:", column_vector_T.shape)

Nhfycgjyjdfybq column vector: [[10.44 10.87 10.85 10.38 10.82 10.11 10.91 10.63 10.38 10.46]]
Transposed column vector shape: (1, 10)
